# Generated by Django 4.1.7 on 2023-02-20 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='nombre',
            new_name='curso',
        ),
    ]
