# Generated by Django 4.1.7 on 2023-02-21 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_app', '0002_rename_nombre_curso_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregables',
            name='estado_entregado',
            field=models.BooleanField(default=False),
        ),
    ]
